- name: install apache
  yum: name=httpd state=latest

- name: copy httpd.conf
  copy: src=../templates/httpd.conf dest=/etc/httpd/conf/httpd backup=yes

- name: be sure apache is running and enabled
  service: name=httpd state=started enabled=yes
