- name: install redis
  yum: name=redis state=latest enablerepo=epel

- name: be sure redis is running and enabled.
  service: name=redis state=started enabled=yes

- name: chmod redis log file
  shell: chmod 777 /var/log/redis/redis.log